### ISSUE TITLE
Epic - Summer Refactor (starts after TTTF4 mid-June)

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/data-analyses#1122]
### Summary

We've done a lot, so let's take part of June and most of July to look over our projects and refactor/document/improve.

Samer's group will be doing something similar.

## Quick Ideas
* [Portfolio front page](https://analysis.calitp.org/) beautification + standardization
* @shweta487 maintaining AHSC ridership tool and moving it to warehouse v2
* @edasmalchi speedmaps revisions (including CT branding? getting full-width to work, colorblind option?)
* @csuyat-dot bus costs -- general refactor and document, organize code...
* @amandaha8 GTFS Digest refinements (cardinal direction, rewrite functions for less duplication)
   * Finding definitions "where is am_peak defined?" Which shared definitions do we all use?
* CSIS lessons learned -> refactor into general CSIS workflow
* CSIS future scorecards/workflow streamlining (less Excel, less touchpoints, "easily rerun scorecards absent Conveyal change", etc)
* Conveyal adaptors + docs
* Combining various utility functions
* Speeding up JupyterHub launch time? https://github.com/cal-itp/data-infra/issues/3375
* Portfolio script -- multithreading? general qol?
* Warehouse documentation -- how far back can we easily go with v2? is v1 fully gone?

## Linked Issues (add as written)

- [ ] 1. #1131  @shweta487 
    - [ ] #1123 
    - [ ] #1128 
    - [ ] #1130  
- [x] 2. #1142 
- [x] 3. #1129 
- [ ] 4. [CSIS Automation/Refactor ](https://github.com/cal-itp/csis-metrics/issues/70): Issue covers both data pipeline/reporting scorecard improvements and metrics automations
- [ ] 5. Portfolio: Docs & Beautification @edasmalchi  @amandaha8 
     - [x] #1138 
     - [x] #1141 
- [ ] #1140
- [x] #1165 
- [x] #1159 @amandaha8 
- [x] #1135 @amandaha8 
- [x] #1176 @edasmalchi

**Comment by hhmckay** [comment]
https://github.com/cal-itp/csis-metrics/issues/72

**Comment by KatrinaMKaiser** [comment]
Check off when READMEs are updated with new portfolio template:

- [ ] GTFS Digest @amandaha8 
- [ ] Speedmaps @edasmalchi 
- [ ] Monthly NTD Ridership @csuyat-dot 
- [ ] Quarterly Performance Metrics @tiffanychu90 
- [ ] SB125 Route Illustrations @edasmalchi

**Comment by KatrinaMKaiser** [comment]
Substantially complete! 🥇
