### ISSUE TITLE
Epic - Transit Speed Maps Data Source Migration

### ISSUE THREAD

**Issue by KatrinaMKaiser** [cal-itp/data-analyses#1186]
### Summary
* Goal: Refactor CA Transit Speed Maps site to use Segment Speeds table instead of bespoke data processing

### Tasks and responsibilities:
* Incorporate dwell time to full speeds pipeline
* Incorporate aggregation fix to full speeds pipeline
* Incorporate 1-km segments to full speeds pipeline
* Refactor speed maps site data ingestion
* Update and publish revised speeds Open Data, including documentation
* Update speed maps site external-facing documentation (as appropriate)
* Update speed maps site internal-facing documentation/instructions so any analyst can re-run on a monthly cadence 

### Notes, misc:
* Is #1162 still relevant after the aggregation patch? 

### Reviewers [Stakeholders]
1. @tiffanychu90 

## Issues
- [ ] 1. #1183 
- [ ] 2. #1184 
- [ ] TBD

### Deliverables
- [ ]  Updated CA Transit Speeds data in warehouse
- [ ] Updated Speed Maps site
- [ ] Updated Speed Segments data on Open Data Portal
- [ ] Updated Speed Maps site documentation (external-facing and internal-facing)

**Comment by KatrinaMKaiser** [comment]
Closing per discussion w @edasmalchi - will reopen a smaller task to cover open data segment speeds, as part of new epic to cover 2025 speedmaps product roadmap
