### ISSUE TITLE
Epic - GTFS analytics pipeline - stop + operator grains 

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-analyses#1232]
After receiving a research request, use this template to plan and track your work. Be sure to also add the appropriate project-level label to this issue (eg gtfs-rt, DLA).

### Summary
* GTFS digest shows mostly operator and route-direction stats across `schedule`, `speeds`, `rt vs schedule`.
   * The operator section shows GTFS schedule stats + NTD 
* Make concerted effort to develop our tables supporting visualizations in coherent way
   * Additional operator tables (Juan Matute) for work within `rt vs schedule` (operator grain)
   * Current research on transit bunching `rt vs schedule` (stop grain)
   * Evan's request for stop map to be included in GTFS digest (stop grain) can be combined with Julian's work related to stops

### Tables 

|  | operator | route-dir | stop |
|---|---|---|---|
| schedule | operator_ scheduled_stats | schedule_stats_by_ route_direction | TODO: schedule_stats_by_ stop |
| segment speeds | N/A | average_segment_speeds average_speedmap_ segment_speeds | N/A |
| summary speeds | TODO? how would we average this  if routes are different lengths? would simple average be ok? | average_summary_speeds | N/A |
| rt vs schedule | rt_v_scheduled_operator | rt_v_scheduled_routes | TODO: transit bunching  work |

[gtfs_analytics_data](https://github.com/cal-itp/data-analyses/blob/main/_shared_utils/shared_utils/gtfs_analytics_data.yml)
* Similar to `sched_route_direction_metrics: "schedule_route_dir/schedule_route_direction_metrics"` and `vp_route_direction_metrics: "vp_route_dir/route_direction_metrics"`, we want
   * `sched_stop_metrics`: capture any stop-level metric we can calculate (`n_trips, n_arrivals, n_routes, n_hours_in_service`
   * `vp_stop_metrics`: transit bunching 

## Issues

- [ ] 1. rt stop grain -- similar to how schedule route-direction stats are merged with RT vs schedule outputs before going into GTFS digest #1099
- [x] 2. rt vs schedule operator grain: #1259 
- [x] 3. scheduled stop grain #1241
