### ISSUE TITLE
Epic - Cal-B/C Updates Prioritization

### ISSUE THREAD

**Issue by shweta487** [cal-itp/data-analyses#1237]
## Summary
The benefit-cost analysis tool developed by Caltrans is under consideration for enhancement particularly in integrating key components such as Equity, Climate Factors and Active Transportation. This issue focuses on the initial work identified after receiving the request from Transportation Economics Branch at Caltrans to upgrade and update the current model. A list of 13 changes has been identified with varying timeframes for implementation, of which DDS has prioritized a few for immediate attention. This issue will capture work updates, along with identified research questions that arise during the process of integrating the new data sources.

#### Tidying the data structure
- Move parameter tables onto different sheets for easier updates.
- [ ]  Create new parameter sheet for each metric.
- [ ]  Refer rest of the documents/ calculations to the new tidier parameter sheets and hide those.
- Maintain the parameters summary sheet for ease of review.
- [ ]  Refer parameter sheets to the individual metric sheets.

#### Updating emissions parameters
- Include CH4 and C2O.
- [ ] Review CARB guidance and reach out to CARB to get the latest emission data. 
- Update [EMFAC](https://arb.ca.gov/emfac/scenario-analysis/generate-template) data.
- [ ] Add additional emission columns to Emission Parameters and Emission Calculations tabs.
- [ ] Edit name manager to include new emission columns.

#### Expanding safety variables to incorporate more crash types
- [ ] Coordinate with Transportation Economics Division to identify potential updates.
- [ ] Expand safety variables from 4 to 6.

#### Incorporating “welfare weights”
- [ ] Coordinate with Sustainability to get weights out of EQI.

**Comment by shweta487** [comment]
Moved to CalBC repo.
