### ISSUE TITLE
Epic - deprecate legacy speedmaps and review associated modules

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/data-analyses#1308]
### Summary
* Now that speedmaps are deployed via the `rt_segment_speeds` pipeline, it's soon time to finally deprecate the old code. We do need to ensure we can generate the SCCP/LPP Level of Transit Delay metric via the new pipeline first, and let's also use this opportunity to clean up `shared_utils.rt_utils`.

### Reviewers [Stakeholders]

1. @tiffanychu90 
2. @edasmalchi 

## Issues/parts

- [x] create functions to run SCCP/LPP level of transit delay metric using `rt_segment_speeds` pipeline
- [x] consolidate time of day related functions (including `shared_utils.rt_utils.categorize_time_of_day`) and definitions in `shared_utils.time_helpers`, migrate existing uses
- [ ] ~consolidate and document functions related to webapp mapping (some in `ca_transit_speed_maps/speedmap_utils` for now)~ largely duplicated in #1140 
- [ ] ~remove `rt_delay/rt_analysis` package~
- [x] review `shared_utils.rt_utils` for deprecated functions, other opportunities to consolidate
- [ ] review docs site, remove rt_analysis module docs

**Comment by edasmalchi** [comment]
Hi @tiffanychu90, @KatrinaMKaiser mentioned that you'd like an update on this one.

I'm not actively working on it now, so broadly speaking it shouldn't block anything. I still think consolidating `shared_utils` time of day functions could be worthwhile, and I could take that on starting in a few weeks.

I actually don't think I should delete `rt_delay/rt_analysis` quite yet -- only because it could still be useful for looking at data from the early days of the v2 warehouse/before the `rt_segment_speeds` pipeline was running. Of course it could be substantially slimmed down since we aren't running it on new data.

**Comment by edasmalchi** [comment]
Sure thing, I'll take a pass at removing/consolidating

**Comment by edasmalchi** [comment]
@tiffanychu90 just scrubbed a bunch from `rt_utils` via #1433
