### ISSUE TITLE
Research: All GTFS-RT Speedmaps and Tools available for Better Bus Challenge

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/data-analyses#176]
## Question

How can ongoing RT speed/delay work best support Caltrans districts and other jurisdictions in improving the bus experience, statewide?

## Metrics

- [x] Speedmaps and other metrics ran for each operator with available RT data
- [x] Results segmented by district, reproducible, and accessible alongside other ongoing analysis work ([989](cal-itp/data-analyses#155), etc)
- [x] Instructions/documentation drafted
- [ ] Instructions/documentation reviewed and complete

## Data sources

* GTFS-RT vehicle positions (existing raw table in warehouse)
* GTFS Schedule data (in warehouse)
