### ISSUE TITLE
Epic - Analytics portfolio deployment

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-analyses#227]
After receiving a research request, use this template to plan and track your work. Be sure to also add the appropriate project-level label to this issue (eg gtfs-rt, DLA).

### Summary
* Set up workflow to use `papermill` to parameterize notebooks, `netlify` to build Jupyterbook
* This epic focuses mostly on the infrastructure / workflow setup related to allowing analysts to deploy their analysis

### Research required:
* Build and clean up deployment tests 
* How to inject parameters in Markdown cells (`display(Markdown())` for headers don't play nicely with Jupyterbook
* Different levels of parameterization - single notebook with multiple parameters, multiple notebooks sharing parameters, no parameterization (just deploy to site)
* Organization of sites - split up yaml so multiple notebooks sharing same params can use yaml anchors
* Give `index.html` the UI/UX treatment
* Credentials for netlify - service user for site? single service user? individual credentials for analysts? accommodate collaborative analyses
*  Document workflow for analysts in docs 

### Notes, misc:
* 

### Reviewers [Stakeholders]

1. @edasmalchi - RT (lots of parameters)
2. @natam1 - DLA (cleanest example to get working)
3. @tiffanychu90 - parallel corridors (multiple notebooks or unparameterized)

## Issues

- [x] 1. MVP with prototype notebook: #99, #103 
- [x] 2. inject lots of params into Markdown header cells: #119 
- [x] 3. workflow tweaks: #134, #189, #213, #249
- [x] 4. Hub environment / quality of life: #202, #205
- [x] 5. documentation: https://github.com/cal-itp/data-infra/pull/1521, #278, https://github.com/cal-itp/data-infra/pull/1560

### Deliverables
[Sites hosted here.](https://analysis.calitp.org)
