### ISSUE TITLE
Epic - Migrate over to use `gtfs_utils`

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-analyses#363]
After receiving a research request, use this template to plan and track your work. Be sure to also add the appropriate project-level label to this issue (eg gtfs-rt, DLA).

### Summary
* Migrate queries related to GTFS schedule to use `gtfs_utils` in scripts, notebooks. Go through everything and standardize wherever possible.

### Research required:
* Set up data catalog of dates we have each month, downloaded for HQTA / Traffic Ops -> `shared_utils.rt_dates.py`

### Notes, misc:
* 

### Reviewers [Stakeholders]

1.

## Issues

- [x] 1. #357 - rewrite `gtfs_utils` so the queries are not unnecessarily large
- [x] 2. #358 - hqta downloading data steps
- [x] 3. #362 - update `rt_utils` to rely on `gtfs_utils`, but with additional steps of checking for cached files, force clear, etc
- [x] 4. #352 - update `traffic_ops` , creation of monthly update to open data portal, sync with hqta dates each month, use `gtfs_utils` instead of writing fresh queries
- [x] 5. #372  - add a function to compile all the cached `trips`, `routelines`, `stops`, `stop_times` datasets by operator into 1 parquet to use in other projects
- [x] 6. #402 - run through rest of open data workflow to push `hqta` and `traffic_ops` datasets through  

### Deliverables
* Notebooks, dashboards, narratives, presentation details.

**Comment by tiffanychu90** [comment]
Closing - completed full workflow where a fresh month's data is downloaded using `gtfs_utils` and run through the open data portal process
