### ISSUE TITLE
Epic - Open Data Publishing 2023

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-analyses#544]
After receiving a research request, use this template to plan and track your work. Be sure to also add the appropriate project-level label to this issue (eg gtfs-rt, DLA).

### Summary
* Easily track the PRs related to monthly updates to open data portal
* Going forward, no need to open an issue each month, just link PR here
* **Reference: [Monthly dates downloaded for open data](https://github.com/cal-itp/data-analyses/blob/main/_shared_utils/shared_utils/rt_dates.py)**
* Publish 6 geospatial datasets each month: 
   * `ca_hq_transit_areas` (HQTA polygons)
   * `ca_hq_transit_stops` (HQTA points)
   * `ca_transit_routes` (initially Traffic Ops request)
   * `ca_transit_stops` (initially Traffic Ops request)
   * `speeds_by_stop_segments`
   * `speeds_route_time_of_day`
* Steps to produce open data portal:
   * add current month's date in `shared_utils/rt_dates`
   * download GTFS scheduled `trips`, `stops`, `shapes`, `stop_times`, and `vehicle_locations` tables for a single day: `cd gtfs_funnel/ && make funnel_gtfs_data`
   * HQ areas/stops datasets: `cd high_quality_transit_areas/ && make hqta_data` (interspersed with notebook checks)
   * GTFS stops/routes geospatial datasets: `cd open_data/ && make create_gtfs_schedule_geospatial_open_data`
   * update metadata XML and publish to enterprise geodatabaes: `cd open_data/ && make compile_open_data_portal` (this step is more manual)

### 2023 open data (stable phase)

* Breaking change: using v2 warehouse: #607 
* Jan 2023: #614 
* Feb 2023: #654 
* Mar 2023: #686 
* Apr 2023: #721 
* May 2023: #756 
* Jun 2023: #786 
* Jul 2023: #808 (first month for 2 speed datasets to be included)
* Aug 2023: #840, #855 
* Sep 2023: #878 
* Oct 2023: #929, #932
* Nov 2023: #952 (first month for interpolated methodology for speeds)
* Dec 2023: #967 

### 2022 open data (development phase)
* Dec 2022: #580 
* Nov 2022: #553 
* Oct 2022: #480
* Sep 2022: #449

#### Wrangling data for publishing
- [x] 1. HQTA v1 
#11
#12 
#22 
#39
#130
#248
- [x] 2. first pass at publishing HQTA and Traffic Ops 
#160
#174
#283
#297
- [x] 3. HQTA rewrites
#321
- [x] 4. Traffic Ops rewrite
#352 
#### Enterprise Geodatabase 
- [x] 1. getting initial metadata set up
 #281
 #283
 #296
 #304
 - [x] 2. from zipped file geodatabase to enterprise geodatabase
 #399
- [x] 3. moving from ArcGIS desktop to ArcGIS Pro
#429
#508 
- [x] 4. changes to Caltrans required metadata items
#802, #810, #813
- [x] 5. investigate any options to make metadata updates easier
#953

**Comment by tiffanychu90** [comment]
Close epic for 2023 PRs related to open data publishing. Use new epic for 2024.
