### ISSUE TITLE
Epic - Daskify RT segment speeds

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-analyses#592]
After receiving a research request, use this template to plan and track your work. Be sure to also add the appropriate project-level label to this issue (eg gtfs-rt, DLA).

### Summary
* Pilot the route segments concept to see how speeds get calculated at the by route segment-trip level
* Assemble all the tables that are needed for pipeline and decide priority of which ones can be moved to dbt first
* [RT segment speeds pipeline Google Doc](https://docs.google.com/document/d/1XlYcXG7BJLcEUH9Kg9zqNTY7IWcyu9iX8aroNhNtzlA/edit)

#### Steps 

1. cut segments (route segments or stop segments)
1. spatial join vehicle positions by route-direction to the segments (use delayed after looping within routes for operator) (`A1`)
1. pare down vehicle positions to just enter/exit within a segment + drop unusable trips (trips < 10 min of vp data). should exclude trips with too little info or `trip_id is None` at the start, then pare down (`A2`)
1. do linear referencing within segments to get `distance_elapsed` and `time_elapsed`, and calculate speeds. save as partitioned parquets (`A3`)

### Set up tables for exploration
- [x] 1. #593 
- [x] 2. #600
- [x] 3. #605 
- [x] 4. #643 
- [x] 5. #662  
- [x] 6. #670 
- [x] 7. #674 (rerun Feb 2023 to fix UTC vs Pacific and download 2 dates of vp)
- [x] 8. #743, #765 refactor stop segments workflow

### Diagnostics
- [x] 1. #594: where are errors for too high or too low speeds coming from? 
- [x] 2a. #595: generate trip-level diagnostics
- [x] 2b. #604: visualize these in a notebook. goal: get thresholds for usable trips without sacrificing short trips that have valid and complete vehicle positions
- [x] 3. #648: find the most aggregation we can do for `stop`-level metrics and stop-to-stop segments. 
- [ ] 4. #663: how to/if we should aggregate stop-level metrics within route/stop segments -- skip this 
- [x] 5. #668: compare RT trip time elapsed vs scheduled trip times and minutes of trips with RT vp data

### Refine Data Processing
- [x] 1. #705: circular / loop / inlining of routes: carve out separate data processing 
- [x] 2. #751 
- [x] 3. #761
- [x] 4. #790 
- [ ] 5. #764, #804
- [ ] 6. #811

**Comment by tiffanychu90** [comment]
Speeds by segments analytics pipeline takes roughly ~1.5 hrs to create the 2 open data layers related to speeds. 
Next: use new epic for road segments.
