### ISSUE TITLE
Epic - Open data / reporting workflows v1 to v2

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-analyses#632]
After receiving a research request, use this template to plan and track your work. Be sure to also add the appropriate project-level label to this issue (eg gtfs-rt, DLA).

### Summary
* Track all the research requests related to moving open data or reporting-type analytics workflows into v2
* Highlight notebooks where diagnostics were done

### `shared_utils`
- [x] mainly `gtfs_utils`, but also `geography_utils`, `portfolio_utils`: #564  
- [x] `portfolio_utils`: #626 (need to decide whether decoded `base64_url` is ok as identifier)

### HQTA
- [x] #607 

### Traffic Ops `routes` and `stops`
- [x] #607  

### Quarterly Performance Metrics
- [x] #625  (move `bus_service_utils/create_parallel_corridors.py` into v2) 
- [x] #626 (diagnostics for v1 and v2 parity...decide to overwrite v1 with new workflow). overwrite portfolio for `v1_service_hours` in new workflow, leave `endpoint_delay` as is.
   - [step by step, how routes are categorized and service hours aggregated: v1 to v2 parity](https://github.com/cal-itp/data-analyses/blob/main/quarterly_performance_objective/v1_v2_parity.ipynb) 
   - [historical/quarterly dates, aggregated service hours: v1 to v2 parity](https://github.com/cal-itp/data-analyses/blob/main/quarterly_performance_objective/v1_v2_historical_parity.ipynb)
- [ ] TODO: overwrite portfolio with v2 for `service_hours` and `endpoint_delay`
- [ ] TODO: endpoint delay (transit reliability metric) for v2 

### Speeds by Segment
- [x] #643: Move segment speeds tables from v1 to v2
