### ISSUE TITLE
Epic - CSIS Metric Example Scoring

### ISSUE THREAD

**Issue by KatrinaMKaiser** [cal-itp/data-analyses#818]
### Summary
This issue is for tracking programming work on scoring SCCP/TCEP Cycle 3 projects with quantitative metrics developed by DDS/ESTA. Link PRs to this issue. If committing directly to `main`, mention this issue in the commit message.

### Research required:
* Think about: what are the pain points in scoring a large number of projects, and how can it be improved for Cycle 4? 

### Notes, misc:
A lot of work will also live outside of code on GitHub and is documented in shared CT Sharepoint/Teams. 

### Reviewers [Stakeholders]
- Safety @KatrinaMKaiser 
- Accessibility/DAC Accessibility/Mode Shift @natam1 @hhmckay @edasmalchi 
- Land Use / Natural Resources @KatrinaMKaiser 
- VMT @hunterowens 
- DAC Traffic @hunterowens @hhmckay @KatrinaMKaiser 
- Freight TBD

## Issues/PRs

- [x] 1a. #834 geography ETL @amandaha8 
- [x] 1b. #830 Data Entry ETL
- [x] 2. #830 Includes Safety
- [x] 3. #842 Land Use and Natural Resources
- [ ] 4. #857 in-progress Accessibility and friends
- [ ] 5. #856 in-progress DAC Traffic

### Deliverables
* Week of 7/25: Distribute projects to assignees, develop training guide, conduct training, distribute GIS input assignment, complete Freight and Traffic Impacts metrics
* Week of 7/31: Complete GIS assignment, begin accessibility metrics scoring, complete Safety, VMT, and Land Use / Natural Resources scoring. 
* Week of 8/7: Complete Accessibility / Mode Shift/  DAC accessibility, complete Freight and Traffic Impacts Metrics
* Week of 8/14: QA/QC, executive review, 8/17 dry run of presentation 
* Week of 8/21: District Workshops 
* Week of 8/28: Comments, District Specific Proposal Scoring

**Comment by KatrinaMKaiser** [comment]
Closing this issue to prep for migration to new CSIS metrics repo 😄. Example scoring for workshops is substantially complete!
