### ISSUE TITLE
Epic - GTFS Schedule to RT Metrics

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-analyses#824]
After receiving a research request, use this template to plan and track your work. Be sure to also add the appropriate project-level label to this issue (eg gtfs-rt, DLA).

### Summary
* All exploratory and analytics metrics related to linking schedule tables to RT 
* Use epic to implement metrics in Prof Greg Newmark's papers 
* Potential outputs: an RT version of `stop_times`, spatial accuracy, how many minutes of scheduled service have RT vp or average number of vp per trip, etc 
* Do not use this epic for speed-related work, which is a deep-dive on vehicle positions data

### Reviewers [Stakeholders]
* @tiffanychu90 
* @edasmalchi 
* @amandaha8 

### Processing
- [x] 1. #785 
- [x] 2. #930 

### Tables
- [x] 1. `spatial_accuracy`: #820 
- [x] 2. `rt_stop_times`: #954 
- [x] 3. trip-level metrics (spatial accuracy, vp pings per minute, vp completeness metric): #936 
- [x] 4. aggregate trip-level to route-direction metrics #966 

### Exploratory
- [ ] 1. #968
