### ISSUE TITLE
Epic - Transit speeds on road segments

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-analyses#916]
After receiving a research request, use this template to plan and track your work. Be sure to also add the appropriate project-level label to this issue (eg gtfs-rt, DLA).

### Summary
Calculate speeds over road segments (aggregate across operators / routes / trips)

### Research required:
* Move the processing steps for speeds by stop segments and adapt to road segments. Most of the scripts can be lifted, but there are a couple that will need to be tweaked.

### Roads Prep

- [x] 1. #605 
- [x] 2. #1062 more stable cutting of roads, 1 km and 2 mi segment lengths 

### vp to roads
- [x] 1. sjoin methodology, don't know how to combine roads with shapes and somehow keep ordering #921 
- [x] 2. nearest neighbor methodology attempts 
#951
#956 
#965
- [x] 3. Nearest neighbor approach successful on 25 shapes #1062 
- [ ] 4. Scale nearest neighbor -- can't do it without re-calculating everything, which is not ideal. Ideally, we want to use what we've calculated and use it for a different segment.

### model vp path 
Create a unified framework for taking `fct_vehicle_locations` and fill it in with modeled vp points in between (every 5 seconds). 
* Input various segment endpoints to calculate speed and delta meters / seconds 
   * stop to stop segments would use stop positions 
   * road segments would use 1 km road endpoints as "stop positions"
   * could handle a general case of every 100m along vp path too
- [x] 1. #1361 

### Deliverables
* [Makefile](https://github.com/cal-itp/data-analyses/blob/d6e833a1d1e9b272bc37835c19ab19bba251fe0f/rt_segment_speeds/scripts/Makefile) 
* Roads prep (1 time): `make census_roads_preprocessing` 
* Each date: `make modeled_road_segment_speeds`, find the relevant roads that intersect with the vp path, and calculate speeds for every segment in that road (some will be NaNs!)
* [New datasets created](https://github.com/cal-itp/data-analyses/blob/d6e833a1d1e9b272bc37835c19ab19bba251fe0f/_shared_utils/shared_utils/gtfs_analytics_data.yml) 
* Caveats: 
   * not production ready because we haven't visualized outputs yet
   * especially what we're doing with `fct_vehicle_locations` looks like it can be moved directly into warehouse
   * would likely have to handle the fact that sjoin of vp path to roads doesn't handle direction
