### ISSUE TITLE
Epic - Statewide Transit Priority Data

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/data-analyses#973]
### Summary

We have a lot of data about transit _provision_ and _performance_, but only limited insights into the location and type of transit priority _infrastructure_ deployed across California.

### Research required:

* Where are the various kinds of transit priority measures (bus lanes, queue jumps, transit signal priority, etc...) on California's transportation system (not just Caltrans' State Highway System)?
* Which projects implemented those transit priority measures, and when did that implementation occur? (optional: how were those projects planned? Which entities sponsored them?)
* Which transit operators/GTFS feeds are associated with each transit priority project?
* How can we structure and store this data to support internal and external research, including potential open data publication?
* Which other efforts (agency ID, etc) should this dataset integrate with? Can it use some sort of shared project_id?

### Notes, misc:

Our transit speed/delay datasets provide powerful analysis showing the need for transit priority, having this dataset would help us more accurately estimate improvements for potential projects (#889).

Will also help researchers understand if certain transit priority treatments are more effective in certain contexts, or alternatively how expected improvements from the same transit priority treatment vary across contexts (some of which may be captured in #955).

If an intervention was deployed in the last couple years (within our GTFS-RT archive period), it should be possible to do before/after evaluation.

#### dim_interventions

`project_id, intervention_type, is_full_time, start_time, end_time, includes_weekends, geometry`

(projects with multiple interventions, like a bus lane and transit signal priority, would have multiple rows…

#### dim_projects

`project_id, agency_id, plan_start_date, cons_start_date, opening_date, project_cost, organization_source_record_id, etc…`

### Reviewers [Stakeholders]

@edasmalchi 
@tiffanychu90 

## Issues

- [ ] 1. #
- [ ] 2. #

### Deliverables
* Notebooks, dashboards, narratives, presentation details.

**Comment by julianofhernandez** [comment]
Here is my branch from SFMTA data import with all my work going into data-analyses/transit_priority_infrastructure/ 

https://github.com/cal-itp/data-analyses/tree/sfmta-tsp

**Comment by mrtopsyt** [comment]
Refactor ToDo List

- [ ] Get the data to make all cells within `Bus Speeds.ipynb` run correctly
- [ ] Refactor the functions in `Bus Speeds.ipynb` to create a script to generate the graphs in the notebook
- [ ] Create a notebook to easily create charts given a project ID
- [ ] Determine next steps for new visualizations, ex: summary charts to show the speed differences for different improvements

**Comment by KatrinaMKaiser** [comment]
Note from Susie Lindsay: Yusuf Shatnawi in Traffic Ops is working on an on-system version of this data. Find a time to connect.
