### ISSUE TITLE
Epic - GTFS Digest (exploratory portfolio)

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-analyses#989]
After receiving a research request, use this template to plan and track your work. Be sure to also add the appropriate project-level label to this issue (eg gtfs-rt, DLA).

### Summary
* Track the portfolio work displaying everything we can display with GTFS schedule, speeds, RT vs schedule across all our 4 major workstreams within GTFS (schedule, speeds, RT vs schedule, predictions)
* Outline all the differences in columns so we can land on a standardized way to approach this
   * Make sure every dataset has similar columns so we can merge in our time-series datasets 
   * Keep track of the tables we have created  / aggregated and use this to inform any new tables we are creating

### Speed Tables

**GCS** 
* `SEGMENT_GCS/rollup_singleday/` 
* `SEGMENT_GCS/rollup_multiday/`
* [Makefile](https://github.com/cal-itp/data-analyses/blob/main/rt_segment_speeds/scripts/Makefile) and [data catalog](https://github.com/cal-itp/data-analyses/blob/main/_shared_utils/shared_utils/gtfs_analytics_data.yml)

| **dataset** | **grain** | **geometry** | **time_category** | **single_multi** | **operator_ids** | **timeseries_postprocessing** |
|---|---|---|---|---|---|---|
| shape-stop_segments | (shape_array_key)  shape_id stop_sequence | segment_geom (select one trip per shape) | peak,  off peak, all-day | single <br>multi | (gtfs_dataset_key) org_source_record_id, org_name | cannot be used for multiple  months, as shape_id will appear distinct even in a  6 month period |
| route_direction- stop_segments | route_id, direction_id,  stop_pair | segment_geom | peak,  off peak, all-day | single | (gtfs_dataset_key) org_source_record_id, org_name | put through script to  standardize / parse route_id over time so we can identify the same route over time  (route_id2) |
| route_direction- stop_segments | route_id, direction_id, stop_pair | segment_geom  | peak, offpeak, all-day weekday, weekend, month, year | multi | (gtfs_dataset_key) org_source_record_id, org_name | put through script to  standardize / parse route_id over time so we can identify the same route over time  (route_id2) |
| trip avg speed | trip_instance_key | tabular | has time_of_day column,  but is disaggregated | single | gtfs_dataset_key |  | not used beyond single day |
| route_direction avg speed | route_id, direction_id | common_shape geom | peak, offpeak, all-day | single <br> multi | (gtfs_dataset_key) org_source_record_id, org_name | put through script to  standardize / parse route_id over time so we can identify the same route over time  (route_id2) |

### RT vs Schedule Tables

**GCS** 
* `RT_SCHED_GCS/vp_trip/` 
* `RT_SCHED_GCS/vp_route_dir/`
* [Makefile](https://github.com/cal-itp/data-analyses/blob/main/rt_scheduled_v_ran/scripts/Makefile) and [data catalog](https://github.com/cal-itp/data-analyses/blob/main/_shared_utils/shared_utils/gtfs_analytics_data.yml)

| dataset | grain | geometry | time_category | single_multi | operator_ids | timeseries_postprocessing |
|---|---|---|---|---|---|---|
| trip | trip_instance_key | tabular |  has time_of_day column,  but is disaggregated | single | gtfs_dataset_key  | not used beyond single day |
| route-direction | route_id, direction_id | tabular | peak, offpeak, all-day | single | (gtfs_dataset_key) org_source_id, org_name | put through script to  standardize / parse route_id over time so we  can identify the same  route over time (route_id2) |

### Schedule Tables

**GCS** 
* `RT_SCHED_GCS/schedule_trip/` 
* `RT_SCHED_GCS/schedule_route_dir/`
* [Makefile](https://github.com/cal-itp/data-analyses/blob/main/gtfs_funnel/Makefile) and [data catalog](https://github.com/cal-itp/data-analyses/blob/main/_shared_utils/shared_utils/gtfs_analytics_data.yml)

| dataset | grain | geometry | time_category | single_multi | operator_ids | timeseries_postprocessing |
|---|---|---|---|---|---|---|
| trip | trip_instance_key | tabular | has time_of_day column,  but is disaggregated | single | (gtfs_dataset_key) org_source_id, org_name |  not used beyond single day |
| route-direction | route_id, direction_id | tabular | peak, offpeak, all-day | single | (gtfs_dataset_key) org_source_id, org_name | put through script to  standardize / parse route_id over time so we  can identify the same  route over time (route_id2) |
| monthly route-direction service | route_id, direction_id | tabular | time_of_day, day_type | multiple (month aggregation)| source_record_id | put through script to  standardize / parse route_id over time so we can identify the same  route over time (route_id2) |

## Issues

- [x] 1. refactor `segment_speeds` #992, #1023,
- [x] 2. refactor `schedule` #1011 
- [x] 3. refactor `rt_vs_schedule`: #1016,  #1046
- [x] 4. metrics shakedown: #1059
   - [x] analytics pipeline for metrics shakedown #1060 
- [x] 5. documentation effort #1069

**Comment by tiffanychu90** [comment]
Thanks @amandaha8 for all your work on this...closing this epic now.
